I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 93, in script
    init python:
  File "game/script.rpy", line 104, in <module>
    Main.main()
NameError: name 'Main' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Laura Luo\Desktop\renpy-6.99.12.4-sdk\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\Laura Luo\Desktop\renpy-6.99.12.4-sdk\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/script.rpy", line 93, in script
    init python:
  File "C:\Users\Laura Luo\Desktop\renpy-6.99.12.4-sdk\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Laura Luo\Desktop\renpy-6.99.12.4-sdk\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 104, in <module>
    Main.main()
NameError: name 'Main' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
hacktx17 1.0
